server:
  port: 8082
spring:
  application:
    name: Micro-service-Restaurant
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:restaurants
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

